# -*- coding: utf-8 -*-
"""prep_json_fine_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AabHjR0_OeW4XSXd1sAwY6T4xjRrRj3y
"""

!pip install jsonlines

import openai
import jsonlines
import pandas

from google.colab import drive, userdata,  output
drive.mount('/content/drive')

client = openai.OpenAI(api_key = userdata.get('OPENAI_API_KEY'))

def get_samples(df):
    """ Generate samples from data frame.

    Args:
        df: data frame containing samples.

    Returns:
        List of samples in OpenAI format for fine-tuning.
    """
    samples = []
    for _, row in df.iterrows():

        text = row['text']
        user_message = {'role':'user', 'content':text}

        label = row['sentiment']
        assistant_message = {'role':'assistant', 'content':label}

        sample = {'messages':[user_message, assistant_message]}
        samples += [sample]

    return samples

if __name__ == '__main__':

  """
  for Script Invoking from command line with argparse ex- python3 Copy of '/content/drive/My Drive/Colab Notebooks/DataScience+GPT/Data/textanalysis/train_reviews.csv'
                                      '/content/drive/My Drive/Colab Notebooks/DataScience+GPT/Data/textanalysis/train_reviews.json'
  """


    parser = argparse.ArgumentParser()
    parser.add_argument('in_path', type=str, help='Path to input')
    parser.add_argument('out_path', type=str, help='Path to output')
    args = parser.parse_args()

    df = pandas.read_csv(args.in_path)
    samples = get_samples(df)

    with jsonlines.open(args.out_path, 'w') as file:
        for sample in samples:
            file.write(sample)