# -*- coding: utf-8 -*-
"""Copy of Transcribing audio files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFmQQ3EiphtOLVbh2H8eWR60keogFsh1
"""

import argparse
import openai
import pandas as pd
import time
from IPython.display import Markdown, display, Image
from google.colab import files
import base64
import os
import requests
import shutil
import cv2

from google.colab import drive, userdata
from openai import OpenAI
drive.mount('/content/drive')

!pip install sounddevice
!pip install scipy
!pip install playsound

try:
    API_KEY = userdata.get('OPENAI_API_KEY')
    if not API_KEY:
        raise ValueError("API key not found. Please add it to Colab Secrets.")
except ImportError:
    # Fallback for environments other than Colab, though not recommended
    API_KEY = os.environ.get("OPENAI_API_KEY")
    if not API_KEY:
        raise ValueError("API_KEY environment variable not set.")

client = openai.OpenAI(api_key= userdata.get('OPENAI_API_KEY'))


def transcribe(audio_path):
    """ Transcribe audio file to text.

    Args:
        audio_path: path to audio file.

    Returns:
        transcribed text.
    """
    with open(audio_path, 'rb') as audio_file:
        transcription = client.audio.transcriptions.create(
            file=audio_file, model='whisper-1')
        return transcription.text

if __name__ == '__main__':

   """
  for Script Invoking from command line with argparse ex- python3 Copy of Transcribing audio files.py
                                      "/content/drive/MyDrive/Colab Notebooks/DataScience+GPT/Data/audio_data/kingdomofhappiness_12_krishnamurti_64kb.mp3"
  """

    parser = argparse.ArgumentParser()
    parser.add_argument('audiopath', type=str, help='Path to audio file')
    args = parser.parse_args()

    transcript = transcribe(args.audiopath)
    print(transcript)

audiopath = "/content/drive/MyDrive/Colab Notebooks/DataScience+GPT/Data/audio_data/kingdomofhappiness_12_krishnamurti_64kb.mp3"

transcript = transcribe(audiopath)
display(Markdown(transcript))